Dev
X9Developers/block-explorer pull request #268
Opened 2021-02-24 19:51 UTC by midasdev711

### Problem

Explain the context and why you're making that change.  What is the
problem you're trying to solve? In some cases there is not a problem
and this can be thought of being the motivation for your change.

### Solution

Describe the modifications you've done.

### Result

What will change as a result of your pull request? Note that sometimes
this section is unnecessary because it is self-explanatory based on
the solution.

If you changed the UI, please include screenshots.

2021-04-13 17:57 UTC, adinael commented on web-ui/src/environments/environment.ts
> +    url: 'https://xsnexplorer.io/api',
this line should not be changed.

2021-04-18 23:02 UTC, AlexITC requested changes
I left some preliminary comments, overall, please take the comments for anything else that I haven't reviewed, these are some patterns I found:
- Its not clear that every dependency is necessary, from the npm ones to the modules depending on other modules.
- The code style is not consistent to what is already in the code, sometimes it isn't even consistent with the new code being written.
- Some function/variable names aren't clear.
- Lack of testing for important functions like money transformation, while I don't expect extensive testing, at least the core functionality can have a decent coverage.
- Usage of `any` when it doesn't seem necessary, Typescript is useless in this case.


Thanks.

2021-04-18 23:02 UTC, AlexITC commented on web-ui/angular.json
> +            "scripts": ["node_modules/jquery/dist/jquery.min.js",
Mixing jquery with angular is usually a bad idea, what approaches have you considered that led you to still require jquery?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/angular.json
> +              "node_modules/bootstrap/dist/js/bootstrap.js"]
I think the explorer already uses https://valor-software.com/ngx-bootstrap/#/, what's the need behind bringing bootstrap separately?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/angular.json
> +              "./node_modules/ngx-ui-switch/ui-switch.component.css"
Is this component ever used?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "test": "ng test --no-watch --no-progress --browsers=ChromeHeadlessCI",
Add a new command instead

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "prod": "ng build --prod"
Rename this to `buiild-prod` instead

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "@angular-devkit/build-angular": "^0.10.7",
While this is nice, you will likely have a hard time getting the tests to pass, what has forced you to upgrade?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "@syncfusion/ej2-angular-inputs": "^18.4.47",
How is this being used?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "connect-history-api-fallback": "^1.6.0",
How is this being used?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "express": "^4.16.4",
This is a backend dependency being added to a frontend app, I'm interested to know if this is really required and why

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "jquery": "^3.5.1",
As pointed out in another commnet, jquery is usually not recommended in angular projects, what prevent us to remove it?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/package.json
> +    "lottie-web": "^5.7.6",
Can you give me some examples where this library is used?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/server.js
> +const app = express();
Isn't this already handled by angular?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/tsconfig.json
> +    "skipLibCheck": true,
From the official [docs](https://www.typescriptlang.org/tsconfig#skipLibCheck), its preferred to make sure that the same library has a single version in our code, try that instead of adding this config

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/styles.css
> +  background: #222534 url("data:image/svg+xml;utf8,<svg viewBox='0 0 140 140' width='24' height='24' xmlns='http://www.w3.org/2000/svg' ><g><path d='m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-5
Wouldn't it be better to take this svg to its own file?

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/styles.css
> +    padding-left: 0 !important;
`!important` is something that is generally avoided unless there is no other way, I see quite a lot of times this is being used, please consider avoiding it

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/index.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
Try not mixing two ways for importing scripts, npm is the way we are using, also, npm imports jquery which is imported again.

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/assets/Updating.json
> +{"v":"5.5.7","fr":29.9700012207031,"ip":0,"op":60.0000024438501,"w":96,"h":96,"nm":"Comp 2","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"pointer","sr":1,"ks":{"o":{"a":0,"k":100,"ix":1
What's the purpose of this file? also, make sure to be consistent with the names, this is the only one starting with upper case.

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/app.module.ts
> +// import { NgxBootstrapSliderModule } from 'ngx-bootstrap-slider';
Remove if this is not used

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/app.component.html
> +  <ng-http-loader [filteredUrlPatterns]="['/blocks$']"></ng-http-loader>
I think that `http-loader` doesn't work anymore

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/utils.ts
> +export function truncate(fullStr, frontChars, backChars, separator = null) {
Typescript is useless if you use everything as `any`, make sure to specify types.

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/utils.ts
> +export function amAgo(timestamp: number): string {
Use a function name that's clear enough, also, include tests.

If this function was copied from somewhere else, add the source in a comment, also, consider using moment.js which already handles the corner cases properly

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/utils.ts
> +export function numberWithCommas(x) {
Typescript is useless if you use everything as `any`, make sure to specify types.

Also, add tests

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/utils.spec.ts
> +  it('should truncate the string', (() => {
Add better tests

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/pipes/explorer-amount.pipe.ts
> +    {
This is not consistent to how the if-else are being written in the code, we need a code formatter

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/pipes/explorer-amount.pipe.ts
> +  transform(currency: any, digit: number = 8, fillZero:Boolean = false): string {
> fillZero:Boolean

Add space after the colon

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/pipes/explorer-amount.pipe.ts
> +  zeroFill( number: string, width: number ): string {
Its not clear what this does, ideally, add a couple of tests

2021-04-18 23:02 UTC, AlexITC commented on web-ui/src/app/pipes/pipes.module.ts
> +        CommonModule,
I don't see how the pipes module could depend on forms/router/etc, make sure to do some clean up in the other modules too

2021-04-20 13:29 UTC, midasdev711 commented on web-ui/src/app/pipes/explorer-amount.pipe.ts
> +  zeroFill( number: string, width: number ): string {
That's for this case.

{{ 8456.789 | explorerAmount }}  => 8,456.789
{{ 8456.789 | explorerAmount:4:true }}  => 8,456.7890

2021-04-21 08:49 UTC, midasdev711 commented on web-ui/angular.json
> +              "./node_modules/ngx-ui-switch/ui-switch.component.css"
Yes, in dex host calculator

2021-04-21 08:50 UTC, midasdev711 commented on web-ui/angular.json
> +              "node_modules/bootstrap/dist/js/bootstrap.js"]
I removed them.

2021-04-21 08:50 UTC, midasdev711 commented on web-ui/angular.json
> +            "scripts": ["node_modules/jquery/dist/jquery.min.js",
Removed it.

2021-05-17 16:18 UTC, AlexITC requested changes
Overall I took a quick look to this huge change, I'd like to merge it as soon as possible, I'll approve when the PR gets these changes:
- Enable the tests and get them passing in the CI
- Format the code properly, there are some html pieces not aligned.
- Remove unused/commented code
- There are some critical pieces that I want you tor write tests for, like the calculator functions
- Try to avoid using `any` types, and specify types when possible.

Thanks.

2021-05-17 16:18 UTC, AlexITC commented on web-ui/package.json
> +    "start": "node server.js",
Please explain what's the usefulness to include express because angular already has an embedded server for dev purposes, if this is not necessary, remove it

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/addresses/address-details/address-details.component.ts
> +  loadingType = 2;
Use a enum instead of int values, or at least, create constants representing the possible statuses instead of using magic numbers

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/addresses/address-details/address-details.component.ts
> +  interval = null;
What's this for? you forgot to define the type

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/addresses/address-details/address-details.component.ts
> +  isLoading: boolean;
you likely need a `isLoading` per component loaded asynchronously, otherwise, there will be conflicts while loading transactions and tpos contracts

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/addresses/address-details/address-details.component.ts
> +    // this.limit = getNumberOfRowsForScreen(height);
Remove the unused code instead of commenting it, unless there is a reason to keep, in which case, add the necessary comment

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/blocks/block-list/block-list.component.ts
> +    loadingType = 2;
Same comment about magic numbers

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/calculator/calculator.component.ts
> +  holdAmount = null;
Missing type

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/calculator/calculator.component.ts
> +  xsnPriceInputValue = null;
Make sure to address the missing type specified in most of the changes

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/calculator/calculator.component.ts
> +export class CalculatorComponent implements OnInit, AfterViewChecked {
This component has quite a lot of functions that could be taken out of the component, make sure to tests those, its pretty important to get the correct data for users

2021-05-17 16:18 UTC, AlexITC commented on .circleci/config.yml
> +      # - run: cd web-ui && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
Tests are expected to run in the CI

2021-05-17 16:18 UTC, AlexITC commented on web-ui/src/app/components/nodes/masternode-details/masternode-details.component.html
> +  </div>
Please make sure that all the changes have properly formatted code

2021-05-18 08:21 UTC, midasdev711 commented on web-ui/package.json
> +    "start": "node server.js",
That's for staging server. (http://staging.xsnexplorer.io/)
In the staging server, I build the project and run it with node server.
You can check that in server.js.

2021-05-18 09:01 UTC, midasdev711 commented on web-ui/src/app/components/calculator/calculator.component.ts
> +  holdAmount = null;
Added type.

2021-05-18 09:01 UTC, midasdev711 commented on web-ui/src/app/components/calculator/calculator.component.ts
> +  xsnPriceInputValue = null;
Added type.

2021-05-18 09:08 UTC, midasdev711 commented on web-ui/src/app/components/addresses/address-details/address-details.component.ts
> +  interval = null;
Added type.
That's to save interval id so that the component can remove interval when it's destroyed.

2021-05-18 14:27 UTC, AlexITC commented on web-ui/package.json
> +    "start": "node server.js",
In my opinion, this is not necessary for the project, I'd suggest keeping this change in your local machine only

2021-05-18 14:30 UTC, AlexITC commented on web-ui/package.json
> +    "start": "node server.js",
In fact, given that it is staging, why can't you use `ng server` instead?

2021-05-21 20:30 UTC, midasdev711 commented on .circleci/config.yml
> +      # - run: cd web-ui && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
There is no e2e test in the project now. So I have to start from scratch.

2021-05-21 20:30 UTC, midasdev711 commented on .circleci/config.yml
> +      # - run: cd web-ui && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
Can you give me the scope of the test?

2021-05-21 20:31 UTC, midasdev711 commented on .circleci/config.yml
> +      # - run: cd web-ui && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
Which workflow should be tested with protractor?

2021-05-21 20:56 UTC, AlexITC commented on .circleci/config.yml
> +      # - run: cd web-ui && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
Apologize, you are right that we don't have e2e tests, this is fine.

2021-06-20 16:42 UTC, AlexITC commented
Superseded by #329 .

2021-06-20 16:42 UTC, closed without merging